### ISSUE TITLE
Add team name and board numbers #team-games channel announcements

### ISSUE THREAD

**Issue by pom-pom** [Lichess4545/heltour#177] opened 2017-07-17 12:19 UTC
Idea for #team-games announcements:

Would be nice to see Team names and board numbers there
Something like:
`@player1 board {{number}} of {{team name}} vs @player2, board {{number}} of {{team name}}: {{link}}`

**Comment by glbert-does** [comment] 2023-03-02 16:51
duplicate of #238 as kostasvl mentioned.

**Closed by glbert-does** 2023-03-02 16:51 UTC
