### ISSUE TITLE
Alternate searches should not start automatically if a new opponent was assigned after round start

### ISSUE THREAD

**Issue by hopffgam** [Lichess4545/heltour#435] opened 2022-02-08 16:05 UTC
In the team league after 25 hours each pairing is checked for unresponsive players and alternate searches are started for players that are determined to be unresponsive. The problem is that if a player was waiting for an alternate to be assigned as an opponent, and that alternate gets assigned close before the check, the player only has very little time to contact their opponent to avoid being marked as unresponsive.

This should not happen. As a short term fix, players should probably not be considered unresponsive by our software at all if their opponent has been assigned after round start. Long term fix could be to set a player as unresponsive if they did not contact their opponent within 24 hours after the opponent was assigned to the pairing.

**Comment by glbert-does** [comment] 2022-04-04 16:46
this is basically a duplicate of https://github.com/Lichess4545/heltour/issues/201 i would say.

**Closed** 2022-09-18 21:29 UTC
Labels: [Team], P1 - high, moderation
